### ISSUE TITLE
Clone from .test or .live fails

### ISSUE THREAD

**Issue by mcdwayne** [ataylorme/terminus-site-clone#2]
After successfully cloning from mcdwaynedotcom.dev (WP site) and one of my multidevs I tried from my .live and .test environments  This failed with error:  
[error]  Command `git -C /Users/dwaynemcdaniel/terminus-site-clone-temp/mcdwaynedotcom/ remote set-url origin ` failed with exit code 129 

Here is printout from terminal:
"
~ $terminus site:clone mcdwaynedotcom.live demo4-19-2018.dev

 Are you sure you want to clone from the mcdwaynedotcom.live environment (source) to the demo4-19-2018.dev (destination)? This will completely destroy the destination. A backup will be made first, just in case.
 (yes/no) [no]:
 > yes

 [notice] Importing code on demo4-19-2018.dev with git...
PHP Notice:  Undefined index: git_url in /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php on line 332
PHP Stack trace:
PHP   1. {main}() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:0
PHP   2. Pantheon\Terminus\Terminus->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:44
PHP   3. Robo\Runner->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/src/Terminus.php:103
PHP   4. Symfony\Component\Console\Application->run() /Users/dwaynemcdaniel/terminus/vendor/consolidation/robo/src/Runner.php:193
PHP   5. Symfony\Component\Console\Application->doRun() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:148
PHP   6. Symfony\Component\Console\Application->doRunCommand() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:248
PHP   7. Symfony\Component\Console\Command\Command->run() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:964
PHP   8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Command/Command.php:252
PHP   9. Consolidation\AnnotatedCommand\CommandProcessor->process() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
PHP  10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
PHP  11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
PHP  12. call_user_func_array:{/Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235}() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
PHP  13. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->clonePantheonSite() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
PHP  14. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->importBackup() /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php:136

Notice: Undefined index: git_url in /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php on line 332

Call Stack:
    0.0024     362888   1. {main}() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:0
    0.4116    5573712   2. Pantheon\Terminus\Terminus->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:44
    0.4116    5573736   3. Robo\Runner->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/src/Terminus.php:103
    0.8453    8029272   4. Symfony\Component\Console\Application->run() /Users/dwaynemcdaniel/terminus/vendor/consolidation/robo/src/Runner.php:193
    0.8770    8032312   5. Symfony\Component\Console\Application->doRun() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:148
    0.8892    8032312   6. Symfony\Component\Console\Application->doRunCommand() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:248
    0.8961    8073256   7. Symfony\Component\Console\Command\Command->run() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:964
    0.9000    8117592   8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Command/Command.php:252
    0.9006    8134904   9. Consolidation\AnnotatedCommand\CommandProcessor->process() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
    0.9007    8134904  10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
    0.9031    8149496  11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
    0.9032    8150568  12. call_user_func_array:{/Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235}() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
    0.9032    8150992  13. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->clonePantheonSite() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
    5.4271    9269512  14. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->importBackup() /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php:136

 [notice] /Users/dwaynemcdaniel/terminus-site-clone-temp/mcdwaynedotcom/ already exists for for demo4-19-2018.dev. Fetching the latest...
 [notice] Running git -C /Users/dwaynemcdaniel/terminus-site-clone-temp/mcdwaynedotcom/ remote set-url origin 
usage: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    --push                manipulate push URLs
    --add                 add URL
    --delete              delete URLs

 [error]  Command `git -C /Users/dwaynemcdaniel/terminus-site-clone-temp/mcdwaynedotcom/ remote set-url origin ` failed with exit code 129 
~ $terminus site:clone mcdwaynedotcom.test demo4-19-2018.dev

 Are you sure you want to clone from the mcdwaynedotcom.test environment (source) to the demo4-19-2018.dev (destination)? This will completely destroy the destination. A backup will be made first, just in case.
 (yes/no) [no]:
 > yes

 [notice] Importing code on demo4-19-2018.dev with git...
PHP Notice:  Undefined index: git_url in /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php on line 332
PHP Stack trace:
PHP   1. {main}() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:0
PHP   2. Pantheon\Terminus\Terminus->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:44
PHP   3. Robo\Runner->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/src/Terminus.php:103
PHP   4. Symfony\Component\Console\Application->run() /Users/dwaynemcdaniel/terminus/vendor/consolidation/robo/src/Runner.php:193
PHP   5. Symfony\Component\Console\Application->doRun() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:148
PHP   6. Symfony\Component\Console\Application->doRunCommand() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:248
PHP   7. Symfony\Component\Console\Command\Command->run() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:964
PHP   8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Command/Command.php:252
PHP   9. Consolidation\AnnotatedCommand\CommandProcessor->process() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
PHP  10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
PHP  11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
PHP  12. call_user_func_array:{/Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235}() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
PHP  13. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->clonePantheonSite() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
PHP  14. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->importBackup() /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php:136

Notice: Undefined index: git_url in /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php on line 332

Call Stack:
    0.0003     362888   1. {main}() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:0
    0.1040    5573712   2. Pantheon\Terminus\Terminus->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/bin/terminus:44
    0.1040    5573736   3. Robo\Runner->run() /Users/dwaynemcdaniel/terminus/vendor/pantheon-systems/terminus/src/Terminus.php:103
    0.4364    8029272   4. Symfony\Component\Console\Application->run() /Users/dwaynemcdaniel/terminus/vendor/consolidation/robo/src/Runner.php:193
    0.4476    8032312   5. Symfony\Component\Console\Application->doRun() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:148
    0.4478    8032312   6. Symfony\Component\Console\Application->doRunCommand() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:248
    0.4511    8073256   7. Symfony\Component\Console\Command\Command->run() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Application.php:964
    0.4528    8117592   8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /Users/dwaynemcdaniel/terminus/vendor/symfony/console/Command/Command.php:252
    0.4531    8134904   9. Consolidation\AnnotatedCommand\CommandProcessor->process() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
    0.4531    8134904  10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
    0.4537    8149496  11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
    0.4538    8150568  12. call_user_func_array:{/Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235}() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
    0.4538    8150992  13. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->clonePantheonSite() /Users/dwaynemcdaniel/terminus/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
    4.6271    9269512  14. Pantheon\TerminusSiteClone\Commands\SiteCloneCommand->importBackup() /Users/dwaynemcdaniel/.terminus/plugins/terminus-site-clone-master/src/Commands/SiteCloneCommand.php:136

 [notice] /Users/dwaynemcdaniel/terminus-site-clone-temp/mcdwaynedotcom/ already exists for for demo4-19-2018.dev. Fetching the latest...
 [notice] Running git -C /Users/dwaynemcdaniel/terminus-site-clone-temp/mcdwaynedotcom/ remote set-url origin 
usage: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    --push                manipulate push URLs
    --add                 add URL
    --delete              delete URLs

 [error]  Command `git -C /Users/dwaynemcdaniel/terminus-site-clone-temp/mcdwaynedotcom/ remote set-url origin ` failed with exit code 129

**Comment by ataylorme** [comment]
Thanks for the report @mcdwayne - I'll look into this

**Comment by ataylorme** [comment]
So cloning from test or live would be a significant amount of work as I can't find a good way to get the latest tag for test or live. `git describe --tags --abbrev=0 --match "pantheon_live_*"` comes close but in testing doesn't always get the latest tag.

With the recommended workflow of multidev/feature branches I think it is a very narrow use case for wanting to clone from test or live because dev has changes that aren't deployed yet and should not be included in the merge.

Files and database can also be brought from test/live to dev or a multidev from Terminus or the dashboard before making a clone.

Therefore I am going to move forward with disallowing the clone source to be test or live.
