### ISSUE TITLE
Add link to the https://pantheon.io/docs/terminus/plugins/ in the install instructions

### ISSUE THREAD

**Issue by mcdwayne** [ataylorme/terminus-site-clone#3]
I had to look it up, but I already knew where it was

Either that or just list out the plugin install steps:

Install Plugins
Add plugins within the $HOME/.terminus/plugins directory on your local workstation. You may need to create the $HOME/.terminus/plugins directory if it does not already exist:

mkdir -p $HOME/.terminus/plugins
Download a zip archive of the plugin's most recent release, then install it by unpacking the archive within $HOME/.terminus/plugins:

curl https://github.com/pantheon-systems/terminus-plugin-example/archive/1.x.tar.gz -L | tar -C ~/.terminus/plugins -xvz

**Comment by ataylorme** [comment]
This was added in [this commit](https://github.com/ataylorme/terminus-site-clone/commit/e6749f7016a9c4dbe31b7b55bc4ec2d728ff7ea9).
